package com.jscn.commons.core.utils;

public class ProductScheduledetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column JSCN.PRODUCT_SCHEDULEDETAIL.ID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column JSCN.PRODUCT_SCHEDULEDETAIL.SCID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	private String scid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column JSCN.PRODUCT_SCHEDULEDETAIL.SC_STARTTIME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	private String scStarttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column JSCN.PRODUCT_SCHEDULEDETAIL.SC_ENDTIME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	private String scEndtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column JSCN.PRODUCT_SCHEDULEDETAIL.GROUPID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	private String groupid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column JSCN.PRODUCT_SCHEDULEDETAIL.GROUPNAME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	private String groupname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.ID
	 * @return  the value of JSCN.PRODUCT_SCHEDULEDETAIL.ID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.ID
	 * @param id  the value for JSCN.PRODUCT_SCHEDULEDETAIL.ID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.SCID
	 * @return  the value of JSCN.PRODUCT_SCHEDULEDETAIL.SCID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public String getScid() {
		return scid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.SCID
	 * @param scid  the value for JSCN.PRODUCT_SCHEDULEDETAIL.SCID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public void setScid(String scid) {
		this.scid = scid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.SC_STARTTIME
	 * @return  the value of JSCN.PRODUCT_SCHEDULEDETAIL.SC_STARTTIME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public String getScStarttime() {
		return scStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.SC_STARTTIME
	 * @param scStarttime  the value for JSCN.PRODUCT_SCHEDULEDETAIL.SC_STARTTIME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public void setScStarttime(String scStarttime) {
		this.scStarttime = scStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.SC_ENDTIME
	 * @return  the value of JSCN.PRODUCT_SCHEDULEDETAIL.SC_ENDTIME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public String getScEndtime() {
		return scEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.SC_ENDTIME
	 * @param scEndtime  the value for JSCN.PRODUCT_SCHEDULEDETAIL.SC_ENDTIME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public void setScEndtime(String scEndtime) {
		this.scEndtime = scEndtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.GROUPID
	 * @return  the value of JSCN.PRODUCT_SCHEDULEDETAIL.GROUPID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public String getGroupid() {
		return groupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.GROUPID
	 * @param groupid  the value for JSCN.PRODUCT_SCHEDULEDETAIL.GROUPID
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.GROUPNAME
	 * @return  the value of JSCN.PRODUCT_SCHEDULEDETAIL.GROUPNAME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public String getGroupname() {
		return groupname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column JSCN.PRODUCT_SCHEDULEDETAIL.GROUPNAME
	 * @param groupname  the value for JSCN.PRODUCT_SCHEDULEDETAIL.GROUPNAME
	 * @mbggenerated  Fri Jul 13 17:45:34 CST 2012
	 */
	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}
}